### ISSUE TITLE
关于缩进

### ISSUE THREAD

**Issue by Vv-Good** [GsjzTle/ACM-Templates#5]
### Discussed in https://github.com/GsjzTle/ACM-Templates/discussions/4

<div type='discussions-op-text'>

<sup>Originally posted by **Vv-Good** July 11, 2022</sup>
如何把模板中的缩进取消掉呢?</div>

**Comment by GsjzTle** [comment]
在 `main.tex` 中将 `\setlength{\parindent}{2em}` 注释掉即可。
